### PR TITLE
add support for validation errors

### PR DESCRIPTION
**Pull request by tmc**

### CODE REVIEW

**Review by krolaw — CHANGES_REQUESTED** [review]
Thanks for extracting the errors - it's not my field. There's one issue with your commit. Since the error messages are stored globally, the errors will mix if two documents are parsed at the same time - regardless of the mutex.

I think you need an error "object" that contains the errors and the xmlErrorFunc, created in the ParseSchema func.  I suspect, you won't need then need a mutex...

**Comment by tmc** [comment]
I respect the integer passed in context to direct errors to the right spot. Can you demonstrate this under test?

**Comment by krolaw** [comment]
Sorry my mistake, it's not a data race, but we do have a (slow) memory leak. The errors array can only grow upwards. Setting the main array slot to nil when finished allows the object to be collected but the memory for the slot cannot. Instead of passing the array index, could you pass an array pointer created just for that validation? Then you wouldn't have a memory leak or need a mutex? Apologies, if I have this wrong again.

**Comment by tmc** [comment]
Your assessment is correct, it does represent a slow leak. Changing implementation to be a map with deletion.

**Comment by krolaw** [comment]
Thanks for the patch :-)

**Comment by krolaw** [comment]
Ok, with some experimentation, I've removed the global errors slice and mutex.  Please examine latest commit. Your tests pass, but again, not my area. Your turn to assess.

**Pull request merged**
